/*
 * Copyright (C) 2008-12  Bernhard Hobiger
 *
 * This file is part of HoDoKu.
 *
 * HoDoKu is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HoDoKu is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HoDoKu. If not, see <http://www.gnu.org/licenses/>.
 */
package sudoku;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author  hobiwan
 */
public class ConfigGeneralPanel extends javax.swing.JPanel {

    private JButton[] levelFGButtons;
    private JButton[] levelBGButtons;
    //private JLabel[] levelLabels;
    private DifficultyLevel[] levels;
    private Font[] fonts;
    private JLabel[] fontLabels;
    private double valueFactor;
    private double candidateFactor;
    private double hintFactor;
    private String language;
    private String laf;

    /** All available languages as Locale; synchronized with {@link #availableIsoLanguages} */
    private List<Locale> availableLocales = new ArrayList<Locale>();
    /** All available Languages as ISO 639 2-letter codes. The first item is always "", the second is always "en" */
    private List<String> availableIsoLanguages = new ArrayList<String>();
    /** All available LAFs (first entry is system default); synchronized with {@link #availableLafClassNames) */
    private List<String> availableLafs = new ArrayList<String>();
    /** the class anems of all available LAFs */
    private List<String> availableLafClassNames = new ArrayList<String>();
    
    private Component mainFrame;

    /**
     * Creates new form ConfigGeneralPanel
     */
    public ConfigGeneralPanel(Component mainFrame) {
        this.mainFrame = mainFrame;
        
        initComponents();

        levelFGButtons = new JButton[Options.getInstance().getDifficultyLevels().length];
        levelFGButtons[0] = incompleteFGButton;
        levelFGButtons[1] = easyFGButton;
        levelFGButtons[2] = mediumFGButton;
        levelFGButtons[3] = hardFGButton;
        levelFGButtons[4] = unfairFGButton;
        levelFGButtons[5] = extremeFGButton;
        levelBGButtons = new JButton[Options.getInstance().getDifficultyLevels().length];
        levelBGButtons[0] = incompleteBGButton;
        levelBGButtons[1] = easyBGButton;
        levelBGButtons[2] = mediumBGButton;
        levelBGButtons[3] = hardBGButton;
        levelBGButtons[4] = unfairBGButton;
        levelBGButtons[5] = extremeBGButton;

        fonts = new Font[4];
        fontLabels = new JLabel[4];
        fontLabels[0] = valuesFontLabel;
        fontLabels[1] = candidatesFontLabel;
        fontLabels[2] = printLargeFontLabel;
        fontLabels[3] = printSmallFontLabel;

        // get all available languages
        initLanguages();
        // and all LAFs
        initLafs();

        deleteCursorAfterMsTextField.setDocument(new NumbersOnlyDocument());
        easyTextField.setDocument(new NumbersOnlyDocument());
        mediumTextField.setDocument(new NumbersOnlyDocument());
        hardTextField.setDocument(new NumbersOnlyDocument());
        unfairTextField.setDocument(new NumbersOnlyDocument());
        extremeTextField.setDocument(new NumbersOnlyDocument());
        fontSizeTextField.setDocument(new NumbersOnlyDocument());
        
        initAll(false);
        deleteCursorAfterMsTextField.setEnabled(deleteCursorAfterCheckBox.isSelected());
        fontSizeTextField.setEnabled(! defaultSizeCheckBox.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        easyLabel = new javax.swing.JLabel();
        mediumLabel = new javax.swing.JLabel();
        hardLabel = new javax.swing.JLabel();
        unfairLabel = new javax.swing.JLabel();
        extremeLabel = new javax.swing.JLabel();
        easyTextField = new javax.swing.JTextField();
        mediumTextField = new javax.swing.JTextField();
        hardTextField = new javax.swing.JTextField();
        unfairTextField = new javax.swing.JTextField();
        extremeTextField = new javax.swing.JTextField();
        easyFGButton = new javax.swing.JButton();
        mediumFGButton = new javax.swing.JButton();
        hardFGButton = new javax.swing.JButton();
        unfairFGButton = new javax.swing.JButton();
        extremeFGButton = new javax.swing.JButton();
        easyBGButton = new javax.swing.JButton();
        mediumBGButton = new javax.swing.JButton();
        hardBGButton = new javax.swing.JButton();
        unfairBGButton = new javax.swing.JButton();
        extremeBGButton = new javax.swing.JButton();
        incompleteLabel = new javax.swing.JLabel();
        incompleteFGButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        incompleteBGButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        showCandidatesCheckBox = new javax.swing.JCheckBox();
        showWrongValuesCheckBox = new javax.swing.JCheckBox();
        showDeviationsCheckBox = new javax.swing.JCheckBox();
        saveWindowLayoutCheckBox = new javax.swing.JCheckBox();
        alternativeMouseModeCheckBox = new javax.swing.JCheckBox();
        localLabel = new javax.swing.JLabel();
        localComboBox = new javax.swing.JComboBox();
        lookAndFeelComboBox = new javax.swing.JComboBox();
        lookAndFeelLabel = new javax.swing.JLabel();
        defaultSizeCheckBox = new javax.swing.JCheckBox();
        fontSizeLabel = new javax.swing.JLabel();
        fontSizeTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        valuesLabel = new javax.swing.JLabel();
        candidatesLabel = new javax.swing.JLabel();
        printLargeLabel = new javax.swing.JLabel();
        printSmallLabel = new javax.swing.JLabel();
        valuesFontLabel = new javax.swing.JLabel();
        candidatesFontLabel = new javax.swing.JLabel();
        printLargeFontLabel = new javax.swing.JLabel();
        printSmallFontLabel = new javax.swing.JLabel();
        valuesButton = new javax.swing.JButton();
        candidatesButton = new javax.swing.JButton();
        printLargeButton = new javax.swing.JButton();
        printSmallButton = new javax.swing.JButton();
        valueFactorLabel = new javax.swing.JLabel();
        candidatesFactorLabel = new javax.swing.JLabel();
        hintFactorLabel = new javax.swing.JLabel();
        valueFactorTextField = new javax.swing.JTextField();
        candidateFactorTextField = new javax.swing.JTextField();
        hintFactorTextField = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        shiftKeyCheckBox = new javax.swing.JCheckBox();
        onlySmallCursorsCheckBox = new javax.swing.JCheckBox();
        colorValuesCheckBox = new javax.swing.JCheckBox();
        showSudokuSolvedCheckBox = new javax.swing.JCheckBox();
        deleteCursorAfterCheckBox = new javax.swing.JCheckBox();
        deleteCursorAfterMsTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        toggleFilterAndOrCheckBox = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigGeneralPanel.jPanel1.border.title"))); // NOI18N

        easyLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.easyLabel.mnemonic").charAt(0));
        easyLabel.setLabelFor(easyTextField);
        easyLabel.setText(bundle.getString("ConfigGeneralPanel.easyLabel.text")); // NOI18N

        mediumLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.mediumLabel.mnemonic").charAt(0));
        mediumLabel.setLabelFor(mediumTextField);
        mediumLabel.setText(bundle.getString("ConfigGeneralPanel.mediumLabel.text")); // NOI18N

        hardLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.hardLabel.mnemonic").charAt(0));
        hardLabel.setLabelFor(hardTextField);
        hardLabel.setText(bundle.getString("ConfigGeneralPanel.hardLabel.text")); // NOI18N

        unfairLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.unfairLabel.mnemonic").charAt(0));
        unfairLabel.setLabelFor(unfairTextField);
        unfairLabel.setText(bundle.getString("ConfigGeneralPanel.unfairLabel.text")); // NOI18N

        extremeLabel.setLabelFor(extremeTextField);
        extremeLabel.setText(bundle.getString("ConfigGeneralPanel.extremeLabel.text")); // NOI18N

        extremeTextField.setEditable(false);

        easyFGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        easyFGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        easyFGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        easyFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyFGButtonActionPerformed(evt);
            }
        });

        mediumFGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        mediumFGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        mediumFGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        mediumFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumFGButtonActionPerformed(evt);
            }
        });

        hardFGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        hardFGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        hardFGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        hardFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardFGButtonActionPerformed(evt);
            }
        });

        unfairFGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        unfairFGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        unfairFGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        unfairFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfairFGButtonActionPerformed(evt);
            }
        });

        extremeFGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        extremeFGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        extremeFGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        extremeFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extremeFGButtonActionPerformed(evt);
            }
        });

        easyBGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        easyBGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        easyBGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        easyBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBGButtonActionPerformed(evt);
            }
        });

        mediumBGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        mediumBGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        mediumBGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        mediumBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumBGButtonActionPerformed(evt);
            }
        });

        hardBGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        hardBGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        hardBGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        hardBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardBGButtonActionPerformed(evt);
            }
        });

        unfairBGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        unfairBGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        unfairBGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        unfairBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfairBGButtonActionPerformed(evt);
            }
        });

        extremeBGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        extremeBGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        extremeBGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        extremeBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extremeBGButtonActionPerformed(evt);
            }
        });

        incompleteLabel.setText("jLabel1"); // NOI18N

        incompleteFGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        incompleteFGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        incompleteFGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        incompleteFGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incompleteFGButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        incompleteBGButton.setMaximumSize(new java.awt.Dimension(60, 20));
        incompleteBGButton.setMinimumSize(new java.awt.Dimension(60, 20));
        incompleteBGButton.setPreferredSize(new java.awt.Dimension(60, 20));
        incompleteBGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incompleteBGButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(easyLabel)
                    .addComponent(mediumLabel)
                    .addComponent(hardLabel)
                    .addComponent(unfairLabel)
                    .addComponent(extremeLabel)
                    .addComponent(incompleteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(unfairTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unfairFGButton, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hardFGButton, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mediumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mediumFGButton, 0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(easyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(easyFGButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(extremeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incompleteFGButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(extremeFGButton, 0, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extremeBGButton, 0, 25, Short.MAX_VALUE)
                    .addComponent(unfairBGButton, 0, 25, Short.MAX_VALUE)
                    .addComponent(hardBGButton, 0, 25, Short.MAX_VALUE)
                    .addComponent(mediumBGButton, 0, 25, Short.MAX_VALUE)
                    .addComponent(easyBGButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(incompleteBGButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {easyTextField, extremeTextField, hardTextField, jTextField1, mediumTextField, unfairTextField});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {easyBGButton, extremeFGButton, hardFGButton, mediumFGButton, unfairFGButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(easyLabel)
                            .addComponent(easyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(easyFGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mediumLabel)
                            .addComponent(mediumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mediumFGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hardLabel)
                            .addComponent(hardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hardFGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unfairLabel)
                            .addComponent(unfairTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unfairFGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extremeLabel)
                            .addComponent(extremeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extremeFGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(easyBGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mediumBGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hardBGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unfairBGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extremeBGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incompleteFGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(incompleteLabel)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(incompleteBGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {easyBGButton, easyFGButton, easyTextField, extremeBGButton, extremeFGButton, extremeTextField, hardBGButton, hardFGButton, hardTextField, incompleteBGButton, incompleteFGButton, jTextField1, mediumBGButton, mediumFGButton, mediumTextField, unfairBGButton, unfairFGButton, unfairTextField});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigGeneralPanel.jPanel2.border.title"))); // NOI18N

        showCandidatesCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.showCandidatesCheckBox.mnemonic").charAt(0));
        showCandidatesCheckBox.setText(bundle.getString("ConfigGeneralPanel.showCandidatesCheckBox.text")); // NOI18N
        showCandidatesCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showCandidatesCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        showWrongValuesCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.showWrongValuesCheckBox.mnemonic").charAt(0));
        showWrongValuesCheckBox.setText(bundle.getString("ConfigGeneralPanel.showWrongValuesCheckBox.text")); // NOI18N
        showWrongValuesCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showWrongValuesCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        showDeviationsCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.showDeviationsCheckBox.mnemonic").charAt(0));
        showDeviationsCheckBox.setText(bundle.getString("ConfigGeneralPanel.showDeviationsCheckBox.text")); // NOI18N
        showDeviationsCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        showDeviationsCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        saveWindowLayoutCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.saveWindowLayoutCheckBox.mnemonic").charAt(0));
        saveWindowLayoutCheckBox.setText(bundle.getString("ConfigGeneralPanel.saveWindowLayoutCheckBox.text")); // NOI18N
        saveWindowLayoutCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        saveWindowLayoutCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        alternativeMouseModeCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.alternativeMouseModeCheckBox.mnemonic").charAt(0));
        alternativeMouseModeCheckBox.setText(bundle.getString("ConfigGeneralPanel.alternativeMouseModeCheckBox.text")); // NOI18N
        alternativeMouseModeCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        alternativeMouseModeCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        localLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.localLabel.mnemonic").charAt(0));
        localLabel.setLabelFor(localComboBox);
        localLabel.setText(bundle.getString("ConfigGeneralPanel.localLabel.text")); // NOI18N

        lookAndFeelLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.lookAndFeelLabel.mnemonic").charAt(0));
        lookAndFeelLabel.setLabelFor(lookAndFeelComboBox);
        lookAndFeelLabel.setText(bundle.getString("ConfigGeneralPanel.lookAndFeelLabel.text")); // NOI18N

        defaultSizeCheckBox.setText(bundle.getString("ConfigGeneralPanel.defaultSizeCheckBox.text")); // NOI18N
        defaultSizeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultSizeCheckBoxActionPerformed(evt);
            }
        });

        fontSizeLabel.setLabelFor(fontSizeTextField);
        fontSizeLabel.setText(bundle.getString("ConfigGeneralPanel.fontSizeLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(defaultSizeCheckBox)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(localLabel)
                            .addComponent(lookAndFeelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(localComboBox, 0, 120, Short.MAX_VALUE)
                            .addComponent(lookAndFeelComboBox, 0, 120, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(fontSizeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fontSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(showCandidatesCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showWrongValuesCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showDeviationsCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveWindowLayoutCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alternativeMouseModeCheckBox, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localLabel)
                    .addComponent(localComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookAndFeelLabel)
                    .addComponent(lookAndFeelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(defaultSizeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fontSizeLabel)
                    .addComponent(fontSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showCandidatesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showWrongValuesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showDeviationsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveWindowLayoutCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alternativeMouseModeCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigGeneralPanel.jPanel3.border.title"))); // NOI18N

        valuesLabel.setText(bundle.getString("ConfigGeneralPanel.valuesLabel.text")); // NOI18N

        candidatesLabel.setText(bundle.getString("ConfigGeneralPanel.candidatesLabel.text")); // NOI18N

        printLargeLabel.setText(bundle.getString("ConfigGeneralPanel.printLargeLabel.text")); // NOI18N

        printSmallLabel.setText(bundle.getString("ConfigGeneralPanel.printSmallLabel.text")); // NOI18N

        valuesFontLabel.setText("jLabel1"); // NOI18N

        candidatesFontLabel.setText("jLabel2"); // NOI18N

        printLargeFontLabel.setText("jLabel3"); // NOI18N

        printSmallFontLabel.setText("jLabel4"); // NOI18N

        valuesButton.setText("…"); // NOI18N
        valuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valuesButtonActionPerformed(evt);
            }
        });

        candidatesButton.setText("…"); // NOI18N
        candidatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidatesButtonActionPerformed(evt);
            }
        });

        printLargeButton.setText("…"); // NOI18N
        printLargeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printLargeButtonActionPerformed(evt);
            }
        });

        printSmallButton.setText("…"); // NOI18N
        printSmallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printSmallButtonActionPerformed(evt);
            }
        });

        valueFactorLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.valueFactorLabel.mnemonic").charAt(0));
        valueFactorLabel.setLabelFor(valueFactorTextField);
        valueFactorLabel.setText(bundle.getString("ConfigGeneralPanel.valueFactorLabel.text")); // NOI18N

        candidatesFactorLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.candidatesFactorLabel.mnemonic").charAt(0));
        candidatesFactorLabel.setLabelFor(candidateFactorTextField);
        candidatesFactorLabel.setText(bundle.getString("ConfigGeneralPanel.candidatesFactorLabel.text")); // NOI18N

        hintFactorLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.hintFactorLabel.mnemonic").charAt(0));
        hintFactorLabel.setLabelFor(hintFactorTextField);
        hintFactorLabel.setText(bundle.getString("ConfigGeneralPanel.hintFactorLabel.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueFactorLabel)
                            .addComponent(candidatesFactorLabel)
                            .addComponent(hintFactorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hintFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candidateFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valuesLabel)
                            .addComponent(candidatesLabel)
                            .addComponent(printLargeLabel)
                            .addComponent(printSmallLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printSmallFontLabel)
                            .addComponent(printLargeFontLabel)
                            .addComponent(candidatesFontLabel)
                            .addComponent(valuesFontLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valuesButton)
                            .addComponent(candidatesButton)
                            .addComponent(printLargeButton)
                            .addComponent(printSmallButton))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {candidateFactorTextField, hintFactorTextField, valueFactorTextField});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valuesLabel)
                    .addComponent(valuesFontLabel)
                    .addComponent(valuesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatesLabel)
                    .addComponent(candidatesFontLabel)
                    .addComponent(candidatesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printLargeLabel)
                    .addComponent(printLargeFontLabel)
                    .addComponent(printLargeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printSmallLabel)
                    .addComponent(printSmallFontLabel)
                    .addComponent(printSmallButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueFactorLabel)
                    .addComponent(valueFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(candidatesFactorLabel)
                    .addComponent(candidateFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hintFactorLabel)
                    .addComponent(hintFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resetButton.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.resetButton.mnemonic").charAt(0));
        resetButton.setText(bundle.getString("ConfigGeneralPanel.resetButton.text")); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigGeneralPanel.jPanel4.border.title"))); // NOI18N

        shiftKeyCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.shiftKeyCheckBox.mnemonic").charAt(0));
        shiftKeyCheckBox.setText(bundle.getString("ConfigGeneralPanel.shiftKeyCheckBox.text")); // NOI18N

        onlySmallCursorsCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.onlySmallCursorsCheckBox.mnemonic").charAt(0));
        onlySmallCursorsCheckBox.setText(bundle.getString("ConfigGeneralPanel.onlySmallCursorsCheckBox.text")); // NOI18N

        colorValuesCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.colorValuesCheckBox.mnemonics").charAt(0));
        colorValuesCheckBox.setText(bundle.getString("ConfigGeneralPanel.colorValuesCheckBox.text")); // NOI18N

        showSudokuSolvedCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.showSudokuSolvedCheckBox.mnemonic").charAt(0));
        showSudokuSolvedCheckBox.setText(bundle.getString("ConfigGeneralPanel.showSudokuSolvedCheckBox.text")); // NOI18N

        deleteCursorAfterCheckBox.setText(bundle.getString("ConfigGeneralPanel.deleteCursorAfterCheckBox.text")); // NOI18N
        deleteCursorAfterCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCursorAfterCheckBoxActionPerformed(evt);
            }
        });

        deleteCursorAfterMsTextField.setText(bundle.getString("ConfigGeneralPanel.deleteCursorAfterMsTextField.text")); // NOI18N

        jLabel1.setText(bundle.getString("ConfigGeneralPanel.jLabel1.text")); // NOI18N

        toggleFilterAndOrCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.toggleFilterAndOrCheckBox.mnemonic").charAt(0));
        toggleFilterAndOrCheckBox.setText(bundle.getString("ConfigGeneralPanel.toggleFilterAndOrCheckBox.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showSudokuSolvedCheckBox)
                    .addComponent(colorValuesCheckBox)
                    .addComponent(onlySmallCursorsCheckBox)
                    .addComponent(shiftKeyCheckBox)
                    .addComponent(toggleFilterAndOrCheckBox)
                    .addComponent(deleteCursorAfterCheckBox)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(deleteCursorAfterMsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shiftKeyCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlySmallCursorsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorValuesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showSudokuSolvedCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleFilterAndOrCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteCursorAfterCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCursorAfterMsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                        .addComponent(resetButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        initAll(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void printSmallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printSmallButtonActionPerformed
        chooseFont(3);
    }//GEN-LAST:event_printSmallButtonActionPerformed

    private void printLargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printLargeButtonActionPerformed
        chooseFont(2);
    }//GEN-LAST:event_printLargeButtonActionPerformed

    private void candidatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidatesButtonActionPerformed
        chooseFont(1);
    }//GEN-LAST:event_candidatesButtonActionPerformed

    private void valuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valuesButtonActionPerformed
        chooseFont(0);
    }//GEN-LAST:event_valuesButtonActionPerformed

    private void incompleteBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incompleteBGButtonActionPerformed
        chooseColor(0, false);
    }//GEN-LAST:event_incompleteBGButtonActionPerformed

    private void incompleteFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incompleteFGButtonActionPerformed
        chooseColor(0, true);
    }//GEN-LAST:event_incompleteFGButtonActionPerformed

    private void extremeBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extremeBGButtonActionPerformed
        chooseColor(5, false);
    }//GEN-LAST:event_extremeBGButtonActionPerformed

    private void extremeFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extremeFGButtonActionPerformed
        chooseColor(5, true);
    }//GEN-LAST:event_extremeFGButtonActionPerformed

    private void unfairBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfairBGButtonActionPerformed
        chooseColor(4, false);
    }//GEN-LAST:event_unfairBGButtonActionPerformed

    private void unfairFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfairFGButtonActionPerformed
        chooseColor(4, true);
    }//GEN-LAST:event_unfairFGButtonActionPerformed

    private void hardBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardBGButtonActionPerformed
        chooseColor(3, false);
    }//GEN-LAST:event_hardBGButtonActionPerformed

    private void hardFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardFGButtonActionPerformed
        chooseColor(3, true);
    }//GEN-LAST:event_hardFGButtonActionPerformed

    private void mediumBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumBGButtonActionPerformed
        chooseColor(2, false);
    }//GEN-LAST:event_mediumBGButtonActionPerformed

    private void mediumFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumFGButtonActionPerformed
        chooseColor(2, true);
    }//GEN-LAST:event_mediumFGButtonActionPerformed

    private void easyBGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBGButtonActionPerformed
        chooseColor(1, false);
    }//GEN-LAST:event_easyBGButtonActionPerformed

    private void easyFGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyFGButtonActionPerformed
        chooseColor(1, true);
    }//GEN-LAST:event_easyFGButtonActionPerformed

    private void deleteCursorAfterCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCursorAfterCheckBoxActionPerformed
        deleteCursorAfterMsTextField.setEnabled(deleteCursorAfterCheckBox.isSelected());
    }//GEN-LAST:event_deleteCursorAfterCheckBoxActionPerformed

    private void defaultSizeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultSizeCheckBoxActionPerformed
        if (defaultSizeCheckBox.isSelected()) {
            fontSizeTextField.setEnabled(false);
        } else {
            fontSizeTextField.setEnabled(true);
        }
    }//GEN-LAST:event_defaultSizeCheckBoxActionPerformed
    
    public void okPressed() {
        // levels[0] = INCOMPLETE
        levels[1].setMaxScore(Integer.parseInt(easyTextField.getText()));
        levels[2].setMaxScore(Integer.parseInt(mediumTextField.getText()));
        levels[3].setMaxScore(Integer.parseInt(hardTextField.getText()));
        levels[4].setMaxScore(Integer.parseInt(unfairTextField.getText()));
        Options.getInstance().setDifficultyLevels(Options.getInstance().copyDifficultyLevels(levels));
        
        boolean oldUseDefaultFontSize = Options.getInstance().isUseDefaultFontSize();
        Options.getInstance().setUseDefaultFontSize(defaultSizeCheckBox.isSelected());
        int oldFontSize = Options.getInstance().getCustomFontSize();
        Options.getInstance().setCustomFontSize(Integer.parseInt(fontSizeTextField.getText()));
        Options.getInstance().setShowCandidates(showCandidatesCheckBox.isSelected());
        Options.getInstance().setShowWrongValues(showWrongValuesCheckBox.isSelected());
        Options.getInstance().setShowDeviations(showDeviationsCheckBox.isSelected());
        Options.getInstance().setSaveWindowLayout(saveWindowLayoutCheckBox.isSelected());
        Options.getInstance().setAlternativeMouseMode(alternativeMouseModeCheckBox.isSelected());
        
        Options.getInstance().setDefaultValueFont(fonts[0]);
        Options.getInstance().setDefaultCandidateFont(fonts[1]);
        Options.getInstance().setBigFont(fonts[2]);
        Options.getInstance().setSmallFont(fonts[3]);
        
        try {
            Options.getInstance().setValueFontFactor(Double.parseDouble(valueFactorTextField.getText()));
        } catch (NumberFormatException ex) {
            Options.getInstance().setValueFontFactor(Options.VALUE_FONT_FACTOR);
        }
        try {
            Options.getInstance().setCandidateFontFactor(Double.parseDouble(candidateFactorTextField.getText()));
        } catch (NumberFormatException ex) {
            Options.getInstance().setCandidateFontFactor(Options.CANDIDATE_FONT_FACTOR);
        }
        try {
            Options.getInstance().setHintBackFactor(Double.parseDouble(hintFactorTextField.getText()));
        } catch (NumberFormatException ex) {
            Options.getInstance().setHintBackFactor(Options.HINT_BACK_FACTOR);
        }
        
        if ((! Options.getInstance().isUseDefaultFontSize() && (oldUseDefaultFontSize || oldFontSize != Options.getInstance().getCustomFontSize())) ||
                (Options.getInstance().isUseDefaultFontSize() && ! oldUseDefaultFontSize)) {
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("GeneralConfigPanel.restart_program2"));
        }
        
        language = availableIsoLanguages.get(localComboBox.getSelectedIndex());
        if (! language.equals(Options.getInstance().getLanguage())) {
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("GeneralConfigPanel.restart_program"));
        }
        Options.getInstance().setLanguage(language);
        
        laf = availableLafClassNames.get(lookAndFeelComboBox.getSelectedIndex());
        if (! laf.equals(Options.getInstance().getLaf())) {
            Options.getInstance().setLaf(laf);
            try {
//                if (laf.equals("")) {
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//                } else {
//                    UIManager.setLookAndFeel(laf);
//                }
                SudokuUtil.setLookAndFeel();
                SwingUtilities.updateComponentTreeUI(this);
                SwingUtilities.updateComponentTreeUI(mainFrame);
            } catch (Exception ex) {
                Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Error setting LAF", ex);
            }
        }

        Options.getInstance().setUseShiftForRegionSelect(shiftKeyCheckBox.isSelected());
        Options.getInstance().setOnlySmallCursors(onlySmallCursorsCheckBox.isSelected());
        Options.getInstance().setColorValues(colorValuesCheckBox.isSelected());
        Options.getInstance().setShowSudokuSolved(showSudokuSolvedCheckBox.isSelected());
        Options.getInstance().setDeleteCursorDisplay(deleteCursorAfterCheckBox.isSelected());
        String number = deleteCursorAfterMsTextField.getText();
        if (number == null || number.equals("")) {
            number = "0";
        }
        Options.getInstance().setDeleteCursorDisplayLength(Integer.parseInt(number));
        Options.getInstance().setUseOrInsteadOfAndForFilter(toggleFilterAndOrCheckBox.isSelected());
    }
    
    private void initAll(boolean setDefault) {
        if (setDefault) {
            levels = Options.getInstance().copyDifficultyLevels(Options.DEFAULT_DIFFICULTY_LEVELS);

            defaultSizeCheckBox.setSelected(Options.USE_DEFAULT_FONT_SIZE);
            fontSizeTextField.setText(String.valueOf(Options.CUSTOM_FONT_SIZE));
            showCandidatesCheckBox.setSelected(Options.SHOW_CANDIDATES);
            showWrongValuesCheckBox.setSelected(Options.SHOW_WRONG_VALUES);
            showDeviationsCheckBox.setSelected(Options.SHOW_DEVIATIONS);
            saveWindowLayoutCheckBox.setSelected(Options.SAVE_WINDOW_LAYOUT);
            alternativeMouseModeCheckBox.setSelected(Options.ALTERNATIVE_MOUSE_MODE);
            
            fonts[0] = Options.DEFAULT_VALUE_FONT;
            fonts[1] = Options.DEFAULT_CANDIDATE_FONT;
            fonts[2] = Options.BIG_FONT;
            fonts[3] = Options.SMALL_FONT;
            
            valueFactor = Options.VALUE_FONT_FACTOR;
            candidateFactor = Options.CANDIDATE_FONT_FACTOR;
            hintFactor = Options.HINT_BACK_FACTOR;
            
            language = Options.DEFAULT_LANGUAGE;
            laf = Options.DEFAULT_LAF;
            shiftKeyCheckBox.setSelected(Options.USE_SHIFT_FOR_REGION_SELECT);
            onlySmallCursorsCheckBox.setSelected(Options.ONLY_SMALL_CURSORS);
            colorValuesCheckBox.setSelected(Options.COLOR_VALUES);
            showSudokuSolvedCheckBox.setSelected(Options.SHOW_SUDOKU_SOLVED);
            deleteCursorAfterCheckBox.setSelected(Options.DELETE_CURSOR_DISPLAY);
            deleteCursorAfterMsTextField.setText(String.valueOf(Options.DELETE_CURSOR_DISPLAY_LENGTH));
            toggleFilterAndOrCheckBox.setSelected(Options.USE_OR_INSTEAD_OF_AND_FOR_FILTER);
        } else {
            levels = Options.getInstance().copyDifficultyLevels(Options.getInstance().getDifficultyLevels());
            
            defaultSizeCheckBox.setSelected(Options.getInstance().isUseDefaultFontSize());
            fontSizeTextField.setText(String.valueOf(Options.getInstance().getCustomFontSize()));
            showCandidatesCheckBox.setSelected(Options.getInstance().isShowCandidates());
            showWrongValuesCheckBox.setSelected(Options.getInstance().isShowWrongValues());
            showDeviationsCheckBox.setSelected(Options.getInstance().isShowDeviations());
            saveWindowLayoutCheckBox.setSelected(Options.getInstance().isSaveWindowLayout());
            alternativeMouseModeCheckBox.setSelected(Options.getInstance().isAlternativeMouseMode());
            
            fonts[0] = Options.getInstance().getDefaultValueFont();
            fonts[1] = Options.getInstance().getDefaultCandidateFont();
            fonts[2] = Options.getInstance().getBigFont();
            fonts[3] = Options.getInstance().getSmallFont();
            
            valueFactor = Options.getInstance().getValueFontFactor();
            candidateFactor = Options.getInstance().getCandidateFontFactor();
            hintFactor = Options.getInstance().getHintBackFactor();
            
            language = Options.getInstance().getLanguage();
            laf = Options.getInstance().getLaf();
            shiftKeyCheckBox.setSelected(Options.getInstance().isUseShiftForRegionSelect());
            onlySmallCursorsCheckBox.setSelected(Options.getInstance().isOnlySmallCursors());
            colorValuesCheckBox.setSelected(Options.getInstance().isColorValues());
            showSudokuSolvedCheckBox.setSelected(Options.getInstance().isShowSudokuSolved());
            deleteCursorAfterCheckBox.setSelected(Options.getInstance().isDeleteCursorDisplay());
            deleteCursorAfterMsTextField.setText(String.valueOf(Options.getInstance().getDeleteCursorDisplayLength()));
            toggleFilterAndOrCheckBox.setSelected(Options.getInstance().isUseOrInsteadOfAndForFilter());
        }
        
        initButtons();
        
        incompleteLabel.setText(levels[0].getName() + ":");
        easyLabel.setText(levels[1].getName() + ":");
        mediumLabel.setText(levels[2].getName() + ":");
        hardLabel.setText(levels[3].getName() + ":");
        unfairLabel.setText(levels[4].getName() + ":");
        extremeLabel.setText(levels[5].getName() + ":");
        
        easyTextField.setText(Integer.toString(levels[1].getMaxScore()));
        mediumTextField.setText(Integer.toString(levels[2].getMaxScore()));
        hardTextField.setText(Integer.toString(levels[3].getMaxScore()));
        unfairTextField.setText(Integer.toString(levels[4].getMaxScore()));
        
        for (int i = 0; i < fonts.length; i++) {
            setFont(fonts[i], fontLabels[i]);
        }
        
        valueFactorTextField.setText(Double.toString(valueFactor));
        candidateFactorTextField.setText(Double.toString(candidateFactor));
        hintFactorTextField.setText(Double.toString(hintFactor));

        // set the language combo box
        localComboBox.removeAllItems();
        localComboBox.addItem(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("GeneralConfigPanel.automatic"));
        int languageIndex = 0;
        for (int i = 1; i < availableLocales.size(); i++) {
            localComboBox.addItem(availableLocales.get(i).getDisplayLanguage());
            if (language.equalsIgnoreCase(availableIsoLanguages.get(i))) {
                languageIndex = i;
            }
        }
        localComboBox.setSelectedIndex(languageIndex);
        
        // set laf combo box
        lookAndFeelComboBox.removeAllItems();
        int lafIndex = 0;
        for (int i = 0; i < availableLafs.size(); i++) {
            lookAndFeelComboBox.addItem(availableLafs.get(i));
            if (laf.equals(availableLafClassNames.get(i))) {
                lafIndex = i;
            }
        }
        lookAndFeelComboBox.setSelectedIndex(lafIndex);
    }
    
    private void chooseFont(int index) {
        Font font = MyFontChooser.showDialog(null, java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.choose_font"), fonts[index]);
        if (font != null) {
            fonts[index] = font;
            setFont(fonts[index], fontLabels[index]);
        }
    }
    
    private void setFont(Font font, JLabel label) {
        int style = font.getStyle();
        String styleStr = "";
        switch (style) {
            case Font.PLAIN: styleStr = java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.regular"); break;
            case Font.BOLD: styleStr = java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.bold"); break;
            case Font.ITALIC: styleStr = java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.italic"); break;
            case Font.BOLD + Font.ITALIC: styleStr = java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.bold_italic"); break;
        }
        label.setText(font.getName() + " " + font.getSize() + " " + styleStr);
    }
    
    private void chooseColor(int index, boolean foreGround) {
        Color init = foreGround ? levels[index].getForegroundColor() : levels[index].getBackgroundColor();
        Color color = JColorChooser.showDialog(this, java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("ConfigGeneralPanel.choose_color"), init);
        if (color != null) {
            if (foreGround) {
                levels[index].setForegroundColor(color);
                initButton(levelFGButtons[index], color);
            } else {
                levels[index].setBackgroundColor(color);
                initButton(levelBGButtons[index], color);
            }
        }
    }
    
    private void initButtons() {
        for (int i = 0; i < levelFGButtons.length; i++) {
            initButton(levelFGButtons[i], levels[i].getForegroundColor());
            initButton(levelBGButtons[i], levels[i].getBackgroundColor());
        }
    }
    
    private void initButton(JButton button, Color color) {
        Image img = new BufferedImage(10, 10, BufferedImage.TYPE_INT_RGB);
        Graphics g = img.getGraphics();
        g.setColor(color);
        g.fillRect(0, 0, 10, 10);
        button.setIcon(new ImageIcon(img));
        if (UIManager.getLookAndFeel().getName().equals("CDE/Motif")) {
            button.setBackground(color);
        }
    }
    
    /**
     * Fills {@link #availableIsoLanguages} and {@link #availableLocales} with all
     * languages, that are available as property files. The first entry is always "", which
     * means "use system default". The second entry is always "en" (english is our default language).
     */
    private void initLanguages() {
        availableIsoLanguages.clear();
        availableLocales.clear();
        availableIsoLanguages.add("");
        availableLocales.add(null);
        availableIsoLanguages.add("en");
        availableLocales.add(Locale.ENGLISH);

        // try to load bundles for all existing languages, log those, for which an actual bundle exists
        Locale oldDefault = Locale.getDefault();
        Locale.setDefault(Locale.ENGLISH);
        String[] isoLanguages = Locale.getISOLanguages();
        for (String isoLang : isoLanguages) {
            Locale locale = new Locale(isoLang);
            ResourceBundle bundle = ResourceBundle.getBundle("intl/MainFrame", locale);
            if (bundle.getLocale().getLanguage().equals(isoLang)) {
                availableIsoLanguages.add(locale.getLanguage());
                availableLocales.add(bundle.getLocale());
            }
        }
        Locale.setDefault(oldDefault);
    }
    
    /**
     * Fills {@link #availableLafs} and {@link #availableLafClassNames}. The first entry
     * stands for "system default".
     */
    private void initLafs() {
        UIManager.LookAndFeelInfo[] lafs = UIManager.getInstalledLookAndFeels();
        availableLafs.clear();
        availableLafClassNames.clear();
        availableLafs.add(java.util.ResourceBundle.getBundle("intl/ConfigGeneralPanel").getString("GeneralConfigPanel.system_default"));
        availableLafClassNames.add("");
        for (int i = 0; i < lafs.length; i++) {
            availableLafs.add(lafs[i].getName());
            availableLafClassNames.add(lafs[i].getClassName());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alternativeMouseModeCheckBox;
    private javax.swing.JTextField candidateFactorTextField;
    private javax.swing.JButton candidatesButton;
    private javax.swing.JLabel candidatesFactorLabel;
    private javax.swing.JLabel candidatesFontLabel;
    private javax.swing.JLabel candidatesLabel;
    private javax.swing.JCheckBox colorValuesCheckBox;
    private javax.swing.JCheckBox defaultSizeCheckBox;
    private javax.swing.JCheckBox deleteCursorAfterCheckBox;
    private javax.swing.JTextField deleteCursorAfterMsTextField;
    private javax.swing.JButton easyBGButton;
    private javax.swing.JButton easyFGButton;
    private javax.swing.JLabel easyLabel;
    private javax.swing.JTextField easyTextField;
    private javax.swing.JButton extremeBGButton;
    private javax.swing.JButton extremeFGButton;
    private javax.swing.JLabel extremeLabel;
    private javax.swing.JTextField extremeTextField;
    private javax.swing.JLabel fontSizeLabel;
    private javax.swing.JTextField fontSizeTextField;
    private javax.swing.JButton hardBGButton;
    private javax.swing.JButton hardFGButton;
    private javax.swing.JLabel hardLabel;
    private javax.swing.JTextField hardTextField;
    private javax.swing.JLabel hintFactorLabel;
    private javax.swing.JTextField hintFactorTextField;
    private javax.swing.JButton incompleteBGButton;
    private javax.swing.JButton incompleteFGButton;
    private javax.swing.JLabel incompleteLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox localComboBox;
    private javax.swing.JLabel localLabel;
    private javax.swing.JComboBox lookAndFeelComboBox;
    private javax.swing.JLabel lookAndFeelLabel;
    private javax.swing.JButton mediumBGButton;
    private javax.swing.JButton mediumFGButton;
    private javax.swing.JLabel mediumLabel;
    private javax.swing.JTextField mediumTextField;
    private javax.swing.JCheckBox onlySmallCursorsCheckBox;
    private javax.swing.JButton printLargeButton;
    private javax.swing.JLabel printLargeFontLabel;
    private javax.swing.JLabel printLargeLabel;
    private javax.swing.JButton printSmallButton;
    private javax.swing.JLabel printSmallFontLabel;
    private javax.swing.JLabel printSmallLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JCheckBox saveWindowLayoutCheckBox;
    private javax.swing.JCheckBox shiftKeyCheckBox;
    private javax.swing.JCheckBox showCandidatesCheckBox;
    private javax.swing.JCheckBox showDeviationsCheckBox;
    private javax.swing.JCheckBox showSudokuSolvedCheckBox;
    private javax.swing.JCheckBox showWrongValuesCheckBox;
    private javax.swing.JCheckBox toggleFilterAndOrCheckBox;
    private javax.swing.JButton unfairBGButton;
    private javax.swing.JButton unfairFGButton;
    private javax.swing.JLabel unfairLabel;
    private javax.swing.JTextField unfairTextField;
    private javax.swing.JLabel valueFactorLabel;
    private javax.swing.JTextField valueFactorTextField;
    private javax.swing.JButton valuesButton;
    private javax.swing.JLabel valuesFontLabel;
    private javax.swing.JLabel valuesLabel;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
        
        Locale oldDefault = Locale.getDefault();
        Locale.setDefault(Locale.ENGLISH);
        List<String> availableLanguages = new ArrayList<String>();
        List<Locale> availableLocales = new ArrayList<Locale>();
        String[] isoLanguages = Locale.getISOLanguages();
        for (String isoLang : isoLanguages) {
            Locale locale = new Locale(isoLang);
            String lang = locale.getDisplayLanguage();
            System.out.println("Locale: " + locale.toString() + " (" + lang + ")");
            ResourceBundle bundle = ResourceBundle.getBundle("intl/MainFrame", locale);
            System.out.println("  Returned: " + bundle.getLocale().toString() + " (" + bundle.getLocale().getDisplayLanguage() + " - " + bundle.getString("MainFrame.error") + ")");
            if (bundle.getLocale().getLanguage().equals(isoLang)) {
                availableLanguages.add(locale.getDisplayLanguage());
                availableLocales.add(locale);
                System.out.println("  ADDED");
            }
        }
        System.out.println();
        System.out.println("Sprachen:");
        for (int i = 0; i < availableLanguages.size(); i++) {
            String la = availableLanguages.get(i);
            Locale lo = availableLocales.get(i);
            System.out.println("  " + la + " (" + lo + ")");
        }
        Locale.setDefault(oldDefault);
    }
}
    
